### ISSUE TITLE
Library should return more data than True/False

### ISSUE THREAD

**Issue by sijis** [pyapi-gitlab/pyapi-gitlab#224] opened 2017-05-17 23:03 UTC
Occasionally we run into issues (gitlab issue, code issue, ci issue, etc) and when troubleshooting calls, its difficult to troubleshoot a response to gitlab when the library returns only True or False.

I think it would be great to return json with a message on what it received from gitlab.
The information could be more useful and help in troubleshooting permission/code issues.

**Comment by Sudo-Kid** [comment] 2017-05-17 23:37
The new pattern that we have been implementing throws an error if the return result is not valid for that method. The exception contains the responses status code and body.

Edit: I'm still working on getting all the old methods switched over to the new pattern witch will fix this issue. Though to keep backwards compatibility I'm adding new methods and calling them from the old ones. This will allow users to keep there old code and replace it with new code when/where they want to.

This is also a duplicate of https://github.com/pyapi-gitlab/pyapi-gitlab/issues/193

**Closed as completed** 2017-05-17 23:45 UTC
